{% set name = "Flask-WTF" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e0b8b33ff457ace4983d25a940133efb9be22922d19452f43a5183e862b9a73

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - wheel
    - setuptools

  run:
    - python >=3.6
    - flask
    - wtforms
    - itsdangerous

test:
  imports:
    - flask_wtf
    - flask_wtf.recaptcha

about:
  home: https://github.com/wtforms/flask-wtf
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Simple integration of Flask and WTForms'
  description: |
    Flask-WTF is a simple integration of Flask and WTForms including CSRF,
    file upload and reCAPTCHA.
  dev_url: https://github.com/wtforms/flask-wtf
  doc_url: https://flask-wtf.readthedocs.io/en/stable/
  doc_source_url: https://github.com/wtforms/flask-wtf/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
