travis:
  secure:
    BINSTAR_TOKEN: B1cGE8G4cuMV1yzEnrAJPc4x6Vrnx/HXp28xoBJM3btYn+EkxHpupwzf49lRGoTg4jxXn1Eds/4oEuGvhawQziIuWgTRhFR5eCMn4z+6aUOu1+fMEbai9jzsUER5FG9QgYnVOwBwQXJxrNxvOGlyx3R5u8CzZCbZAiqSSvZrgbuPIoJc6mouSkIn/B5e9XDYRTnVTQYBMzbEbUFE6dxtZ/38CPYu9irzBlNsJloxIBYXGsHKKz0YSTdMzKay9N6+BckTL6F4uszW51c2SRWtTltPtRnr/zm0us/b8epO/2fcUChzddfeba1wn5Y+CDEMOciMOQ8EqzpQKDDc+rGooO0ZvmIbELIlY2hX+nepzblL3NyLB4wZlR429XW+mcClxzsnhLFSjKvyGAgdiqt4URPZqdpqpo9swu+IQScaHrCKs+7Wm0JEZCFMau3Fa9Ai8BdkYH1S4yfCjWKPujC5vmuT7C1mOOxgKMcdn9MPo8VJ+ButWHP/mWKzjMFriYygnwdPn2DILU5M1Fz4/lLPzPD64x/rqu5HZ6eXr4sbTeRdA36yoOKpBBJnI6i0z/kmSYc/5mwjbV0YDK1WP1BgMxlYiVe7yN4RmwyOGFekzk0jc5PkoUUsldA2CRcluENMJytC7i+FW181JDNds1QODhdFB4vl9M9ENboapcdEB5o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
