travis:
  secure:
    BINSTAR_TOKEN: QSD7CRp1h+8ci1zLX6xEyrOSKFwWXM4jx6REPUwYs0WGldRu4x65J4Ot72enAr4ub76hdBy2k7tq11ptMRyT4KiBiXqI4VZAxy9BQQWtoj7NlBwqppOWWvpXJiYgt23LeQ77cSzOox8p99XxnYPnlHVS4dqFxjlokhx6+z3Jg9MEwDkyakj9px8zpgNFilNJdxlDbW4elhnd5z1TDKtREBJ65Gpl3pKMF6+YjEMMGqOFN/aqUFBSEA7aLCpyOA+JBAswaCMj9gPmMZXzO9TTCeZ/n7UtlnG6iIlA8wyfxl51O6wXQqacK1onwdK7Lve7lABw3x/sl8QgxijwhR6uA4MHZFLK8lwIlqcgJ/hZQ6aE67SbOH+4F4tfH66+UuqeZHq9gR7p2Vs3snYtT1ZiHz5T+ghKHUDQXr44i72tdKx8zCuyHVmUh0jqOPnqV2ZvVFTUVxM4dfmWwGZeD1GrFfLbCmsoaZj5AKej1yzNIsgrKb4bJA36wks0/hvu3d03ftjMkGGaAaDJWFXLeFnRJho/qbiPDE8zmj4NFzdMeZrBxsausPTZiFz1P8smKp3qxxdUCF9Srrh5bwcKKVmr07zavCsHaT/88cGfIc4fAwOVtJSrfXJbzkxU6pGxXcHXpL7EUWMSKXmeil5tTIodkWjZZCJztZplt/U/ONjGjdw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
